// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../cc

declare module 'gnfun-cc' {
    import XTween from "gnfun-cc/XTween";
    export { XTween };
}

declare module 'gnfun-cc/XTween' {
    import { Tween } from "cc";
    export default class XTween<T> extends Tween<T> {
            onCompleteNow(func: () => void): XTween<T>;
            /**
                * 迅速完成
                */
            completeNow(): void;
    }
}

